config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :photos, only: :create
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :place
    after_create :send_comment_email
    
    RATINGS = {
        'one star': '1_star',
        'two stars': '2_stars',
        'three stars': '3_stars',
        'four stars': '4_stars',
        'five stars': '5_stars',
    }
    
    def humanized_rating
        RATINGS.invert[self.rating]
    end
    
    def send_comment_email
        NotificationMailer.comment_added(self).deliver
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :place
    
    mount_uploader :photo_url, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :photos
    
    geocoded_by :address
    after_validation :geocode
    
    validates :name, length: {minimum: 3, too_short: "Your place name must include at least 3 characters" }
    validates :address, length: {minimum: 10, too_short: "Please include the full address"}
    validates :description, length: {in: 10...500, too_long: "500 characters is the maximum allowed", too_short: "Please include a valid description" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @place = Place.find(params[:place_id])
        @place.comments.create(comment_params.merge(user: current_user))
        redirect_to place_path(@place)
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:message, :rating)
    end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @place = Place.find(params[:place_id])
        @place.photos.create(photo_params.merge(user:current_user))
        redirect_to place_path(@place)
    end

    private
    
    def photo_params
        params.require(:photo).permit(:photo_url, :caption)
    end
    
   
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def index
        @places = Place.paginate(page: params[:page], per_page: 10)
    end
    
    def new
        @place = Place.new
    end
    
    def create
        @place = current_user.places.create(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def show
        @place = Place.find(params[:id])
        @comment = Comment.new
        @photo = Photo.new
    end
    
    def edit
        @place = Place.find(params[:id])
        
        if @place.user !=current_user
            return render text: 'Not Allowed', status: :forbidden
        end
    end
    
    def update
        @place = Place.find(params[:id])
        
        if @place.user !=current_user
            return render text: 'Not Allowed', status: :forbidden
        end
        
        @place.update_attributes(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :edit, status: unprocessable_entity
        end
    end
    
    def destroy
        @place= Place.find(params[:id])
        if @place.user != current_user
            return render text: 'Not Allowed', status: :forbidden
        end
        
        @place.destroy
        redirect_to root_path
    end
    
    
    private
    
    def place_params
        params. require(:place).permit(:name, :description, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
      
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            New Place 
          <% end %> 
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to  'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      </ul>
    </div>
  </nav>
  
  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= yield %>
  </body>
  
  
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Edit Your Place</h1>
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <br />
        <%= f.submit 'Update', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/index.html.erb
<div class="col-10 offset-1">

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag 'carousel1.jpg', class: 'd-block img-fluid' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'carousel2.jpg', class: 'd-block img-fluid' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'carousel3.jpg', class: 'd-block img-fluid' %>
            </div>
          </div>
        </div>

</div>


<% @places.each do |place| %>
    <div class="booyah-box col-10 offset-1">
        <div class= "row">
            <div class="col-lg-3 col-sm-6"> 
                <% if place.photos.present? %>
                    <%= image_tag place.photos.last.photo_url, :class => 'img-fluid'%>
                <% end %>
            </div>
            <div class="col-lg-9 col-sm-6">
                <h1><%= link_to place.name, place_path(place) %></h1>
                <i><%= place.address %></i><br />
                <p><%= place.description %></p>
            </div>
        </div>
            <% if place.user.present? %>
                <small> <%= place.user.email %></small>
            <% end %>
            
            <% if place.comments.present? %>
                <div class="col-12">
                  <blockquote>
                    <% if place.comments.last.humanized_rating.present? %>
                      <b><%= place.comments.last.humanized_rating %></b> -
                    <% end %>
                    <%= place.comments.last.message %>
                    <small><%= place.comments.last.user.email %></small>
                  </blockquote>
                </div>
            <% end %>
        </div>

<% end %>

<div class="page-nav col-10 offset-1">
    <%= will_paginate @places %>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Enter Your Place Details</h1>
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <br />
        <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
    <div class="row">
      <div class="col-12 col-md-6">
        <h1> <%= @place.name %> </h1>
        <i><%= @place.address %> </i>
        <br /> <br />
        <p><%= @place.description %></p>
      </div>
      
      <div class="col-6 col-med-6">
      
        <% @place.photos.each do |photo| %>
            <b><%= image_tag photo.photo_url, :class => 'img-fluid' %></b> 
               <br>
            <b><%= photo.caption %></b> 
        <% end %>
      </div>
     </div> 
     
     <br>
     <br>
     
  <div class="col-10 offset-1">
   <% if @place.latitude.present? && @place.longitude.present? %>
      <script>
      
      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
      
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });
      
        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
      </script>
      
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB0kzcQcIp9WAnRPo0p-BLRMrO9tl1fL14&callback=initMap">
      </script>
      
      <div id="map"></div>  
    <% end %>
  </div>
    <br />
    
    <div class="float-right">
        <% if current_user && current_user == @place.user %>
            <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', place_path(@place), method: :delete,  data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
        <% end %>
    </div>
    <br />
    <br />
</div>

<div class="clear"></div>



    
<div class="col-10 offset-1">
  <div class="floatright">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Add a Comment
    </button>
    
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#photoModal">
      Add a Photo
    </button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

<div class="clear"></div>



<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Photograph</h4>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :caption %>
          <%= f.input :photo_url, as: :file %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

</div>


<div class="clear"></div>
<div class="col-10 offset-1">
  <h1 class="float-left"> Comments </h1>
  
  <div class="clear"></div>
  
  <div class="row">
    <% @place.comments.each do |comment| %>
      <div class="col-12 col-sm-6">
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
    <div class="row">
        <div class="col-3">
            <%= image_tag 'user.png' %>
        </div>    
        <div class="col-7">
            <h2><%= @user.email %></h1>
            <h4> Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h4>
            <h5> <%= @user.comments.count %> total comments </h5>
            <h5> <%= @user.comments.where(rating: '5_stars').count %> five star reviews </h5>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="booyah-box col-10 offset-1">
    <h1 class="text-center"> My Comments</h1>
      
    <div class="clear"></div>
        <div class="col-12">
            <% @user.comments.each do |comment| %>
                <h3><%= link_to comment.place.name, place_path(comment.place) %></h3>
                <blockquote>
                    <% if comment.humanized_rating.present? %>
                        <b><%= comment.humanized_rating %></b> -
                    <% end %>
                    <%= comment.message %>
                </blockquote>
            <% end %>
        </div>
</div>

<div class="clear"></div>

<div class="booyah-box col-10 offset-1">
    <h1 class="text-center"> My Places</h1>
      <br>
    <% @user.places.each do |place| %>
      <div class="col-12">
        <h2><%= link_to place.name, place_path(place) %></h2><br />
      </div>
    <% end %>
</div>